vich_uploader:
    db_driver: orm

    mappings:
      materiel_image:
        uri_prefix: images/materiel
        upload_destination: '%kernel.project_dir%/public/images/materiel'
        namer: Vich\UploaderBundle\Naming\UniqidNamer

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
