# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    assets:
        roboto-bold-ttf:
            inputs: '@AppBundle/Resources/public/materialize-src/font/roboto/Roboto-Bold.ttf'
            output: 'font/roboto/Roboto-Bold.ttf'
        roboto-bold-woff:
            inputs: '@AppBundle/Resources/public/materialize-src/font/roboto/Roboto-Bold.woff'
            output: 'font/roboto/Roboto-Bold.woff'
        roboto-bold-woff2:
            inputs: '@AppBundle/Resources/public/materialize-src/font/roboto/Roboto-Bold.woff2'
            output: 'font/roboto/Roboto-Bold.woff2'
        roboto-light-ttf:
            inputs: '@AppBundle/Resources/public/materialize-src/font/roboto/Roboto-Light.ttf'
            output: 'font/roboto/Roboto-Light.ttf'
        roboto-light-woff:
            inputs: '@AppBundle/Resources/public/materialize-src/font/roboto/Roboto-Light.woff'
            output: 'font/roboto/Roboto-Light.woff'
        roboto-light-woff2:
            inputs: '@AppBundle/Resources/public/materialize-src/font/roboto/Roboto-Light.woff2'
            output: 'font/roboto/Roboto-Light.woff2'
        roboto-medium-ttf:
            inputs: '@AppBundle/Resources/public/materialize-src/font/roboto/Roboto-Medium.ttf'
            output: 'font/roboto/Roboto-Medium.ttf'
        roboto-medium-woff:
            inputs: '@AppBundle/Resources/public/materialize-src/font/roboto/Roboto-Medium.woff'
            output: 'font/roboto/Roboto-Medium.woff'
        roboto-medium-woff2:
            inputs: '@AppBundle/Resources/public/materialize-src/font/roboto/Roboto-Medium.woff2'
            output: 'font/roboto/Roboto-Medium.woff2'
        roboto-regular-ttf:
            inputs: '@AppBundle/Resources/public/materialize-src/font/roboto/Roboto-Regular.ttf'
            output: 'font/roboto/Roboto-Regular.ttf'
        roboto-regular-woff:
            inputs: '@AppBundle/Resources/public/materialize-src/font/roboto/Roboto-Regular.woff'
            output: 'font/roboto/Roboto-Regular.woff'
        roboto-regular-woff2:
            inputs: '@AppBundle/Resources/public/materialize-src/font/roboto/Roboto-Regular.woff2'
            output: 'font/roboto/Roboto-Regular.woff2'
        roboto-thin-ttf:
            inputs: '@AppBundle/Resources/public/materialize-src/font/roboto/Roboto-Thin.ttf'
            output: 'font/roboto/Roboto-Thin.ttf'
        roboto-thin-woff:
            inputs: '@AppBundle/Resources/public/materialize-src/font/roboto/Roboto-Thin.woff'
            output: 'font/roboto/Roboto-Thin.woff'
        roboto-thin-woff2:
            inputs: '@AppBundle/Resources/public/materialize-src/font/roboto/Roboto-Thin.woff2'
            output: 'font/roboto/Roboto-Thin.woff2'
        material-design-icons-eot:
            inputs: '@AppBundle/Resources/public/materialize-src/font/material-design-icons/Material-Design-Icons.eot'
            output: 'font/material-design-icons/Material-Design-Icons.eot'
        material-design-icons-svg:
            inputs: '@AppBundle/Resources/public/materialize-src/font/material-design-icons/Material-Design-Icons.svg'
            output: 'font/material-design-icons/Material-Design-Icons.svg'
        material-design-icons-ttf:
            inputs: '@AppBundle/Resources/public/materialize-src/font/material-design-icons/Material-Design-Icons.ttf'
            output: 'font/material-design-icons/Material-Design-Icons.ttf'
        material-design-icons-woff:
            inputs: '@AppBundle/Resources/public/materialize-src/font/material-design-icons/Material-Design-Icons.woff'
            output: 
        material-design-icons-woff2:
            inputs: '@AppBundle/Resources/public/materialize-src/font/material-design-icons/Material-Design-Icons.woff2'
            output: 'font/material-design-icons/Material-Design-Icons.woff2'
    filters:
        cssrewrite: ~
        sass: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css: 
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

